import type { Metadata } from "next";
import "./globals.css";
import { ProductProvider } from "@/components/ProductContext";

export const metadata: Metadata = {
  title: "This amazing store – Buy stuff",
  description: "Generated by the amazing group 1",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ProductProvider>
          {children}
        </ProductProvider>
      </body>
    </html>
  );
}
