import type { Metadata } from "next";
import "./globals.css";
import { ProductProvider } from "@/components/ProductContext";
import GlobalHeader from "@/components/GlobalHeader";
import GlobalFooter from "@/components/GlobalFooter";

export const metadata: Metadata = {
  title: "This amazing store – Buy stuff",
  description: "Generated by the amazing group 1",
  keywords: "shoop",
  category: "web shop",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        
        <ProductProvider>
        <GlobalHeader />
          {children}
        <GlobalFooter />
        </ProductProvider>
      </body>
    </html>
  );
}
